[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [
  {access = "read-write", path = ".forge-snapshots/"},
  {access = "read", path = "integrations/hookr/"},
]
libs = ["vendor"]
out = "out"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.30"
src = "src"
via_ir = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
