name: Test Suite

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Foundry Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0

      - name: Install app dependencies
        run: bun install --frozen-lockfile

      - name: Check
        run: ./scripts/check.sh
